### ISSUE TITLE
nextVersion seems to not do anything

### ISSUE THREAD

**Issue by bellini-ea** [f-u-z-z-l-e/semver-plugin#3]
- I have the plugin applied and the semver {} configuration block set the same as the readme shows.
- My gradle.properties has the project.version set to 5.2.1-SNAPSHOT
- I have one git tag on master as v5.2.1
- gradle version is 6.0.1
- gradlew nextVersion does nothing

My semver block
`semver {
        prefix.value( "v")
        preRelease.value("prerc")
        releaseBranch.value("master")
        tagMessage.value("Tagged automatically")
        buildMetadataSeparator.value("-")
 }`

To be upfront, I'm not clear about the git tagging.  All the semver gradle plugins I have investigated do not give examples of how they want or need the git tagging to be done.  There seems to be assumption that the reader knows this already.  Appreciate any help in getting this plugin up and running.

**Comment by alingenhag** [comment]
Hi there

The nextVersion task is used automatically on afterEvaluate project.  Therefore you should not set the version manually by yourself in gradle.properties.

You are right, I should probably not expose it. You don't need to call this task manually. It parses your git history to determine the (next) version that your project should get assigned. So in your case the next version would be v5.2.2 unless your head commit has #minor or #major somewhere in the commit message. Then it would increase the corresponding minor or major part of the version.

To check which version you are currently working on do:
`gradle displayVersion` or
`gradle properties`

Your semver block looks good to me.

Regarding tagging, the plugin will tag your repository and push the tag to your origin repository if so desired (by running the corresponding tasks). Have a look [here](https://github.com/f-u-z-z-l-e/semver-plugin/blob/3501917093d8b40096eaf796494a80f24fc72501/.github/workflows/build.yml#L42)
as I use the plugin on itself.

Hope that helps.
best regards
