### ISSUE TITLE
Versioning Usage Question/Understanding

### ISSUE THREAD

**Issue by bellini-ea** [f-u-z-z-l-e/semver-plugin#4]
I'm learning semver and applying this plugin at the same time so this could just my misunderstanding.

1. I removed "version" from the build.gradle.kts file
2. I ran `gradlew tagHeadCommit` and I got a v0.0.1 tag
3. I created branch and merged a commit to that branch with #minor in the description.  This resulted in `v0.1.0-preRelease-8da4af28`
4. I merged the branch
5. I ran `gradlew dispVersion` and got a tag of `v0.0.2`

I was expecting to v0.1.0 in master as the version because I bumped #minor on my branch.  What am I missing about how this is suppose to work?

My configuration is as follows:
```
semver {
    prefix.value("v") // sets the version prefix. -> v0.0.1
    preRelease.value("preRelease") // sets the pre-release string (default == git branch name)
    releaseBranch.value("master") // sets the git branch name that is considered to be the 'release' branch.
    tagMessage.value("Tagged automatically") // sets the message the tagHeadCommit task should use (default = 'Tagged by 'ch.fuzzle.gradle.semver' gradle plugin.')
    buildMetadataSeparator.value("-") // defines the separator character before buildMetadata. (default = '+')
}

**Comment by alingenhag** [comment]
At the moment that workflow is not supported. I haven't had the need to promote a version on a branch. I'll consider it for a future release though as I think it could be useful. Thanks.
I'm closing this issue for now, and also the other one that you opened.
