### ISSUE TITLE
displayVersion on Release branch notes "next version"

### ISSUE THREAD

**Issue by bellini-ea** [f-u-z-z-l-e/semver-plugin#5]
Scenario:

- release branch set as "release" in plugin configuration
- tagging a commit with 0.1.0 on the release branch
- run gradlew displayVersion on the release branch and the plugin reports 0.2.0.  

Expectation is the version on the release branch is reported as 0.1.0.

**Comment by alingenhag** [comment]
The expectation is wrong. DisplayVersion will always return a version that is "later" than whatever the latest tag in your git repository is.
