### ISSUE TITLE
Additions to Documentation

### ISSUE THREAD

**Issue by StaticNoiseLog** [f-u-z-z-l-e/semver-plugin#9]
Spring Initializr creates build.gradle with a defined "version" field: `version = '0.0.1-SNAPSHOT'`
It would be good to mention in the documentation that this "version" overrides the plugin's version mechanism and that it must be removed from build.gradle in order to use the plugin.

Please also mention that the `nextVersion` task does not produce any output as it is for internal use.

**Comment by alingenhag** [comment]
It is already mentioned here
https://github.com/f-u-z-z-l-e/semver-plugin#version-evaluation
